var express = require('express');
var router = express.Router();
/* GET home page. */

router.get('/', function(req, res, next) {
  res.render('index',{ title: 'Rajaraman Govindasamy',position:"I'm a Software Developer!",indexbut:"ABOUT ME", projhead1:"Academic Background",projhead1_content:"My passion for Computer Science started at a very young age when I was curious to know about how the computer works with immense processing power, the ability to recall anything in an instant and to perform complex tasks.",projhead2:"Bachelor's degree in Computer Science",projhead3:"Master's degree in Computer Science",projhead4:"Industrial Experience",projhead2_content1:"I saw the field of computer science at a different level, not as a machine, rather composed of entities such as operating systems, software, storage and much more.",projhead2_content2:"I took a data mining and warehousing class which got me more interested towards data and to apply the concepts I learned, I did a project to predict the possibility of heart disease in human.",
  projhead2_content3:"After realizing the increasing demand for analysis of video data, I, along with two other members developed an ‘Automated Visual Surveillance System’ to predict the abnormal behavior of humans in certain situations (example) and we presented this work at the International Conference on Computational Techniques and Artificial Intelligence in Pattaya, Thailand in 2011.",projhead2_tag1:"GPA-3.6/4",projhead2_tag2:"DCE, Chennai, India, 2008-2012",projhead3_tag1:"GPA-3.5/4",projhead3_tag2:"University of Texas at Arlington, USA, 2015-2017",projhead3_content1:"I have done an exhilarating four years of under graduation and I wanted to acquire in-depth knowledge in this startling computer science field.",projhead3_content2:"In order to achieve my goal, I joined the computer science master's program at University of Texas at Arlington and successfully graduated in May 2017.",
  projhead3_content3:"My area of interest was software development and database systems. I had the opportunity to learn in-depth software development practices, core data structure concepts, machine learning algorithms, dive deep into the database, emerging cloud technologies and much more.",projhead3_content4:"I developed few Android applications, web applications dealing with Google APIs/ Dropbox APIs from scratch with best software engineering practices and big-data projects with cloud computing frameworks such as Hadoop/ Apache.",projhead4_tag1:"3-YEARS",projhead4_tag2:"Tata Consultancy Services, India       2014-2015",projhead4_tag3:"Cognizant Technology Solutions, India        2012-2014" });
});
module.exports = router;
